name: 'Slack Message Delivery'
description: 'Send message to Slack Chat'
inputs:
  chat_id:
    description: 'Id of a chat where to send message'
    required: true
    type: string
  slack_token:
    description: "Oauth token with a permission to write to chat"
    required: true
    type: string
  message_title:
    description: "Title for the message"
    required: false
    type: string
  custom_message:
    description: "Custom message"
    required: false
    type: string
  job_status:
    description: "Status of a job"
    required: false
    type: string
runs:
  using: 'docker'
  image: './container/Dockerfile'
  args:
    - ${{ inputs.chat_id }}
    - ${{ inputs.token }}
    - ${{ inputs.message_title }}
    - ${{ inputs.job_status }}