name: 'Slack Send Message'
description: 'Send message to the Slack Chat'
inputs:
  chat_id:
    description: 'Id of a chat where to send message'
    required: true
    type: string
  slack_token:
    description: "Oauth token with a permission to write to the chat"
    required: true
    type: string
  message_title:
    description: "Title for the message"
    required: false
    type: string
  custom_message:
    description: "Custom message that will be send to the chat instead of default one"
    required: false
    type: string
  job_status:
    description: "Status of a current job execution"
    required: false
    type: string
  environment:
    description: "Environment for which job is running"
    required: false
    type: string
  app_name:
    description: "Username for app in the chat"
    required: false
    type: string
  app_image:
    description: "Avatar for app in the chat"
    required: false
    type: string
runs:
  using: 'docker'
  image: './container/Dockerfile'
  args:
    - ${{ inputs.chat_id }}
    - ${{ inputs.slack_token }}
    - ${{ inputs.message_title }}
    - ${{ inputs.custom_message }}
    - ${{ inputs.job_status }}
    - ${{ inputs.environment }}
    - ${{ inputs.app_name }}
    - ${{ inputs.app_image }}
