name: 'Slack Send Msg'
description: 'Send message to the Slack'
inputs:
  chat_id:
    description: 'Id of a chat where to send message'
    required: true
    type: string
  slack_token:
    description: "Oauth token with permission to write to the chat"
    required: true
    type: string
  message_title:
    description: "Title for the message"
    required: false
    type: string
  custom_message:
    description: "Custom message that will be sent to the chat instead of the default one"
    required: false
    type: string
  job_status:
    description: "Status of a current job execution"
    required: false
    type: string
  environment:
    description: "Environment in which job is running"
    required: false
    type: string
  app_name:
    description: "Username for the app in the chat"
    required: false
    type: string
  app_image:
    description: "Avatar for the app in the chat"
    required: false
    type: string
runs:
  using: 'docker'
  image: 'docker://s8ckerpunch/slack-send-msg:v0.1'
  args:
    - ${{ inputs.chat_id }}
    - ${{ inputs.slack_token }}
    - ${{ inputs.message_title }}
    - ${{ inputs.custom_message }}
    - ${{ inputs.job_status }}
    - ${{ inputs.environment }}
    - ${{ inputs.app_name }}
    - ${{ inputs.app_image }}
branding:
  icon: 'send'
  color: 'green'
