name: 'Slack Message Delivery'
description: 'Send message to Slack Chat'
inputs:
  chat_id:  # id of input
    description: 'Id of a chat where to send message'
    required: true
    type: string
  token:
    description: "Oauth token with a permission to write to chat"
    required: true
    type: string
  title:
    description: "Title for the message"
    required: true
    type: string
runs:
  using: 'docker'
  image: './container/Dockerfile'
  args:
    - ${{ inputs.chat_id }}
    - ${{ inputs.token }}
    - ${{ inputs.title }}